version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  cron:
    build:
      context: .
      dockerfile: Dockerfile_cron
